default:
  tags:
    - docker
  # Image from https://hub.docker.com/_/gcc/ based on Debian
  image: gcc:9

autotools:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y libogg-dev
        zip
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make distcheck

cmake:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y cmake ninja-build
  script:
    - mkdir _build
    - cmake -S . -B _build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
    - cmake --build _build

doc:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y doxygen graphviz
  script:
    - make -C doc -f Makefile.lite
